### ISSUE TITLE
[UglifyJS]: Transpile to ES5 before publishing to NPM

### ISSUE THREAD

**Issue by joncursi** [cssivision/qrcode-react#18]
I'm working on a NextJS app and [ran into issues building this library in production](https://github.com/zeit/next.js/issues/3553).

There appears to be some ES6 code being used that UglifyJS cannot interpret. Can we transpile this module into ES5 before publishing to NPM?

**Comment by cssivision** [comment]
this problem has been fixed, i will cut a new release.

**Comment by cssivision** [comment]
0.1.16
