### ISSUE TITLE
[0.1.16]: QR Codes no longer render

### ISSUE THREAD

**Issue by joncursi** [cssivision/qrcode-react#19]
I had QR Codes rendering properly on `0.1.15` after using Babili to parse the code, but after upgrading to `0.1.16` my QR codes no longer render and i get this error in console:

![screen shot 2018-01-09 at 11 14 20 pm](https://user-images.githubusercontent.com/4974609/34755594-f2271ee2-f592-11e7-8219-6fca7fc4c135.png)

**Comment by joncursi** [comment]
https://github.com/cssivision/qrcode-react/blob/master/lib/index.js#L110

This looks like the culprit?

**Comment by cssivision** [comment]
in v0.1.16 , just compile the code to es5 before upload to npm, and i test it in create-react-app, i works.

**Comment by joncursi** [comment]
Hmm, I can no longer reproduce this on my end. Gonna close it down!
